import { useParams, Link } from 'wouter';
import { ArrowLeft, FileCode2 } from 'lucide-react';
import {
  getGetMigrationQueryKey, getGetMigrationDiffQueryKey, useGetMigration, useGetMigrationDiff,
} from '@dua/api-client-react';
import { ErrorState, Patch } from './shared';
import { stages } from './dashboard';

function MigrationFrame({ children, active }: { children: React.ReactNode; active: 'workspace' | 'diff' | 'report' }) {
  const { id = '' } = useParams<{ id: string }>();
  const migration = useGetMigration(id, { query: { enabled: !!id, queryKey: getGetMigrationQueryKey(id), refetchInterval: 5000 } });
  if (migration.isLoading) return <div className="page"><div className="skeleton" style={{ width: 170, height: 12 }} /><div className="skeleton" style={{ width: 420, height: 45, marginTop: 12 }} /><div className="stage-track">{stages.map((stage) => <div className="stage" key={stage}><div className="skeleton" style={{ width: 24, height: 24, borderRadius: '50%' }} /><div className="skeleton" style={{ width: 70, height: 10 }} /></div>)}</div><div className="workspace-grid"><div className="card skeleton" style={{ height: 420 }} /><div className="card skeleton" style={{ height: 300 }} /></div></div>;
  if (migration.isError || !migration.data) return <div className="page"><ErrorState message="This migration run is not available." retry={() => void migration.refetch()} /></div>;
  const m = migration.data;
  return <div className="page"><div className="workspace-head"><div><div className="eyebrow">Migration artifact <span className="migration-id">#{m.id}</span></div><div className="migration-title"><h1>{active === 'diff' ? 'Actual diff' : 'Final report'}</h1><span className={`status status-${m.status}`}>{m.status}</span></div><div className="migration-sub"><b>{m.repositoryName}</b> · {m.dependency} · {m.oldVersion} → {m.targetVersion}</div></div><Link href={`/migration/${id}`} className="btn btn-quiet" data-testid="link-back-workspace"><ArrowLeft /> Back to workspace</Link></div><div className="stage-track">{stages.map((stage, index) => { const activeIdx = m.currentStage === 'queued' ? 0 : m.currentStage === 'research' ? 1 : m.currentStage === 'impact-analysis' ? 2 : m.currentStage === 'migration' ? 4 : m.currentStage === 'heal' ? 7 : (m.currentStage === 'complete' || m.currentStage === 'failed' || m.currentStage === 'cancelled') ? 8 : -1; const isDone = m.status === 'completed' || m.status === 'approved' || (activeIdx >= 0 && index < activeIdx); const isActive = activeIdx === index; const isFailedStage = isActive && (m.status === 'failed' || m.status === 'cancelled'); return <div className={`stage ${isDone ? 'done' : ''} ${isActive ? (isFailedStage ? 'active fail' : 'active') : ''}`} key={stage}><div className="stage-dot">{isDone ? '✓' : index + 1}</div><div className="stage-name">{stage}</div></div>; })}</div><nav className="subnav"><Link href={`/migration/${id}`} className={`subnav-link ${active === 'workspace' ? 'active' : ''}`}>Workspace</Link><Link href={`/migration/${id}/diff`} className={`subnav-link ${active === 'diff' ? 'active' : ''}`}>Actual diff</Link><Link href={`/migration/${id}/report`} className={`subnav-link ${active === 'report' ? 'active' : ''}`}>Final report</Link></nav>{children}</div>;
}

export function DiffPage() {
  const { id = '' } = useParams<{ id: string }>();
  const diff = useGetMigrationDiff(id, { query: { enabled: !!id, queryKey: getGetMigrationDiffQueryKey(id) } });
  return <MigrationFrame active="diff">{diff.isLoading ? <div className="card loading-grid" style={{ padding: 20 }}>{[1, 2, 3].map((item) => <div className="skeleton" style={{ height: 130 }} key={item} />)}</div> : diff.isError || !diff.data ? <ErrorState message="The actual diff is not available yet." retry={() => void diff.refetch()} /> : <div><div className="diff-summary"><div className="card diff-stat"><span>Files changed</span><strong>{diff.data.filesChanged}</strong></div><div className="card diff-stat add"><span>Additions</span><strong>+{diff.data.additions}</strong></div><div className="card diff-stat del"><span>Deletions</span><strong>−{diff.data.deletions}</strong></div></div>{diff.data.files.length === 0 ? <div className="card empty" data-testid="state-empty-diff"><div className="empty-icon"><FileCode2 /></div><h3>No file changes reported</h3><p>The agent has not produced a patch for this migration yet.</p></div> : diff.data.files.map((file) => <section className="card diff-file" key={file.path} data-testid={`diff-file-${file.path}`}><div className="diff-file-head"><span className="path">{file.path}</span><span className="file-meta"><span className="add-text">+{file.additions}</span><span className="del-text">−{file.deletions}</span><span>{file.status}</span></span></div><Patch text={file.patch} /></section>)}</div>}</MigrationFrame>;
}
